DROP TABLE IF EXISTS TBL_EMPLOYEES;
DROP TABLE IF EXISTS SCIPLAN;
CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(15) NOT NULL,
  password VARCHAR(50) NOT NULL,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);

CREATE TABLE SCIPLAN (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  creator VARCHAR(15) NOT NULL,
  submittor VARCHAR(15) NOT NULL,
  funding INT NOT NULL,
  objective VARCHAR(50) NOT NULL,
  starsystem VARCHAR(50) NOT NULL,
  schedule DATE NOT NULL,
  telescope_location VARCHAR(50) NOT NULL,
  dataReqs VARCHAR(50) DEFAULT NULL
);